# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81411e87e620cec4e7ee341ba4fd01fd45f6af0497d0ac44825203532df677d1c9ef12346f7c0131311458e46d7f49b87b21afc1a792fb8995e8655e7d963498

test:
  secret_key_base: 8a229d1be5583dadb10e00274acdd98abfc8b06d68c914074e6ef3987ed583acb0d2a38a495996d25dacbee852fbddf1f80738bf2822f349c76aef30f479895d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
